# Generated by Django 4.1.7 on 2023-04-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
