# Generated by Django 4.1.7 on 2023-05-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdsapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=20)),
                ('persongender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Others', 'Prefer not to say')], max_length=10)),
                ('persondob', models.DateField(max_length=20)),
                ('personemail', models.EmailField(max_length=50, unique=True)),
                ('peronsusername', models.CharField(max_length=50, unique=True)),
                ('peronspassword', models.CharField(max_length=50)),
                ('personlocation', models.CharField(max_length=50)),
                ('personcontact', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'person_table',
            },
        ),
    ]
