# Generated by Django 4.1.7 on 2023-05-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdsapp', '0005_bid1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid2',
            fields=[
                ('bidamount', models.PositiveIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('usermail', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'bid2_table',
            },
        ),
    ]
